name: my first workflow

on: push
jobs:
    say-hello:
        runs-on: ubuntu-latest

        steps:
            - name: Print message
              run: echo "Hello, github actions"
            - name: print name
              run: echo "parv"
    say-bye:
        
        runs-on: ubuntu-latest

        steps:
            - name: print 
              run: echo "bye bye" 
    
    test: 
      runs-on: ubuntu-latest

      steps: 
        - name: Checkout code     //clone repo
          uses: actions/checkout@v4
        
        - name : list file
          run: ls

        - name : setup node
          uses: actions/setup-node@v4
        
        - name : check node version
          run: node --version

        - name : install dependencies
          run: npm install

        - name : running test
          run : npm run test 